# Generated by Django 4.1.13 on 2025-02-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MadLibResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjective1', models.CharField(max_length=50)),
                ('software_type', models.CharField(max_length=50)),
                ('programming_language', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('bug_type', models.CharField(max_length=50)),
                ('adjective2', models.CharField(max_length=50)),
                ('verb_ing', models.CharField(max_length=50)),
                ('plural_noun', models.CharField(max_length=50)),
                ('software_company', models.CharField(max_length=50)),
                ('silly_word', models.CharField(max_length=50)),
                ('verb_past', models.CharField(max_length=50)),
                ('famous_person', models.CharField(max_length=50)),
                ('adjective3', models.CharField(max_length=50)),
                ('noun1', models.CharField(max_length=50)),
                ('verb1', models.CharField(max_length=50)),
                ('verb2', models.CharField(max_length=50)),
                ('adjective4', models.CharField(max_length=50)),
                ('noun2', models.CharField(max_length=50)),
            ],
        ),
    ]
